CREATE TABLE REFUGE (
   EMAIL VARCHAR(50) PRIMARY KEY,
   NOM VARCHAR(50),
   NUMTEL INT,
   SECGEO VARCHAR(50),
   DATEOUV DATE,
   DATEFERME DATE,
   NBrREPAS INT,
   TEXTE VARCHAR(50),
   TYPePAYEMENT VARCHAR(20),
   PRIxNUITE DECIMAL,
   PRIX DECIMAL
);

CREATE TABLE REPAS (
    TYPeREPAS VARCHAR(20) PRIMARY KEY
);
CREATE TABLE PROPOSE_REPAS (
   EMAIL REFERENCES REFUGE(EMAIL),
   TYPeREPAS REFERENCES REPAS(TYPeREPAS),
   PRIMARY KEY (EMAIL, TYPeREPAS),
   PRIX DECIMAL
);

CREATE TABLE RESERVATION_REFUGE (
   ID INT PRIMARY KEY,
   DATE_RESERVATION DATE,
   HEURE HOUR,
   REFUGE VARCHAR(50),
   IdMEMBReRESERVE INT,
   NBrNUITS INT,
   NBrREPAsRESERVE INT,
   PRIxTOTAL DECIMAL,
   IdUSER INT,
   EMAIL VARCHAR(50),
   FOREIGN KEY (IdUSER) REFERENCES COMPTE_UTILISATEUR(IdUSER),
   FOREIGN KEY (EMAIL) REFERENCES REFUGE(EMAIL)
);

CREATE TABLE LOCATION_MATERIEL (
   ID INT PRIMARY KEY,
   IdADHERENT INT,
   NbPIECEsRESERV INT,
   DATeRECUP DATE,
   DATeRETOUR DATE, 
   NbPIECEsPERDUES INT,
   FOREIGN KEY (IdUSER) REFERENCES COMPTE_UTILISATEUR(IdUSER)
);

CREATE TABLE COMPTE_UTILISATEUR (
   IdUSER INT PRIMARY KEY,
   COUtRESERV DECIMAL,
   SOMMeMATERIElABIME DECIMAL,
   SOMMeREMBOURSEE DECIMAL
);


CREATE TABLE MEMBRE (
    EMAIlMEMBRE VARCHAR(70),
    MOTDEPASSE VARCHAR(50),
    PRIMARY KEY (EMAIlMEMBRE, MOTDEPASSE),
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    ADrPOST VARCHAR(50),
    IdUSER INT UNIQUE,
    FOREIGN KEY (IdUSER) REFERENCES COMPTE_UTILISATEUR(IdUSER)
);

CREATE TABLE ADHERENT (
    IdADHERENT INT PRIMARY KEY,
    EMAIlMEMBRE REFERENCES MEMBRE(EMAIlMEMBRE),
    MOTDEPASSE REFERENCES MEMBRE(MOTDEPASSE),
    NOM REFERENCES MEMBRE(NOM),
    PRENOM REFERENCES MEMBRE(PRENOM),
    ADrPOST REFERENCES MEMBRE(ADrPOST),
    IdUSER REFERENCES MEMBRE(IdUSER),
    CONSTRAINT ADHERENT_MEMBRE FOREIGN KEY (IdADHERENT) REFERENCES MEMBRE(IdUSER)
);

CREATE TABLE RESERVATION_FORMATION (
   ID INT PRIMARY KEY,
   IdADHERENT INT,
   FORMATIOnINSCRITE VARCHAR(50),
   RANG INT,
   IdUSER INT,
   NUMERO INT, 
   ANNEE INT,
   FOREIGN KEY (IdUSER) REFERENCES COMPTE_UTILISATEUR(IdUSER),
   FOREIGN KEY (NUMERO, ANNEE) REFERENCES FORMATION(NUMERO, ANNEE)
);


CREATE TABLE FORMATION (
   NUMERO INT,
   ANNEE YEAR,
   PRIMARY KEY (NUMERO, ANNEE),
   NOM VARCHAR(50),
   DATeDEM DATE,
   DUREE INT,
   NBrPLACE INT,
   DESC VARCHAR(50),
   PRIX DECIMAL,
   NBrACTIVITE INT
);

CREATE TABLE ACTIVITE (
   NOmACTIVITE VARCHAR(50),
   TYPeACT VARCHAR(50)
);

CREATE TABLE PROPOSE_ACTIVITE_FORM (
   NUMERO REFERENCES FORMATION(NUMERO),
   ANNEE REFERENCES FORMATION(ANNEE),
   NOmACTIVITE REFERENCES ACTIVITE(NomACTIVITE),
   PRIMARY KEY (NUMERO, ANNEE, NOmACTIVITE)

);

CREATE TABLE COMPATIBLE_AVEC_ACTIVITE (
    MARQUE VARCHAR(50),
    MODELE VARCHAR(50),
    ANNEeACHAT INT,

    FOREIGN KEY (MARQUE, MODELE, ANNEeACHAT) REFERENCES LOT(MARQUE, MODELE, ANNEeACHAT),
    NOmACTIVITE REFERENCES ACTIVITE(NOmACTIVITE),
    PRIMARY KEY (MARQUE, MODELE, ANNEeACHAT, NOmACTIVITE)
);

CREATE LOT (
    MARQUE VARCHAR(50),
    MODELE VARCHAR(50),
    ANNEeACHAT INT,
    NbPIECES INT,
    PRIxPERTE DECIMAL,
    TEXTE VARCHAR(100),
    ANNEePEREMPTION INT,
    PRIMARY KEY (MARQUE, MODELE, ANNEeACHAT),
    SOUsCATEGORIE VARCHAR(50),
    FOREIGN KEY (SOUsCATEGORIE) REFERENCES ARBRE(SOUsCATEGORIE)
);
￼
CREATE TABLE PIECES_LOUEES (
    NBrPIECEsLOUEES INT 
);

CREATE TABLE ABRE (
    SOUsCATEGORIE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE EST_PARENT_DE (
    SOUsCATEGORIE VARCHAR(50) PRIMARY KEY,
    FOREIGN KEY (SOUsCATEGORIE) REFERENCES ABRE(SOUsCATEGORIE),
    CATERGORIE VARCHAR NULL,
    CONSTRAINT PARENTE FOREIGN KEY (CATERGORIE) REFERENCES EST_PARENT_DE(SOUsCATEGORIE)
);



